//! Replays the frozen `testvectors/wire/` conformance corpus (`FORMAT.md`
//! §12.3) through the public API.
//!
//! This is FerroCrypt's own replay layer for the corpus it publishes. It
//! validates the manifest grammar and referential integrity, checks every
//! committed digest against the bytes it names, and then asserts each case's
//! recorded outcome. Per §12.1 the assertion maps typed [`CryptoError`] values
//! to stable diagnostic-class identifiers; it never parses English display
//! text, because that text is not part of the cross-language contract.
//!
//! The corpus is regenerated by the ignored `wire_vector_gen` unit test in the
//! library crate and committed by hand.

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use ferrocrypt::{
    ArchiveLimits, CryptoError, Decryptor, FormatDefect, HeaderReadLimits, KdfLimit, KeyReadLimits,
    Passphrase, PrivateKey, ProgressEvent, PublicKey, UnsupportedVersion,
    validate_private_key_file,
};
use sha3::{Digest, Sha3_256};

/// Capabilities this build supports beyond the `0.3.0` baseline. A
/// capability-relative case is asserted only while its capability is absent
/// (`FORMAT.md` §12.2); FerroCrypt implements none of the future versions and
/// types the corpus names, so the set is empty and every stored outcome is
/// asserted.
const DECLARED_CAPABILITIES: &[&str] = &[];

/// The compatibility baseline this build claims (`FORMAT.md` §11.4). Every
/// case must be first required by it or one of its ancestors, because
/// FerroCrypt must pass every case in the corpus it ships.
const CLAIMED_BASELINE: &str = "0.3.0";

fn corpus_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("testvectors/wire")
}

/// Whether the corpus is on disk at all. `Cargo.toml` excludes it from the
/// published crate, so these replays skip there; a checkout always has the
/// directory, and a file missing from inside it still fails loudly below. A
/// corpus deleted from a checkout is caught by `tools/verify_manifests.py`,
/// which CI runs as a job of its own.
fn corpus_present() -> bool {
    corpus_root().is_dir()
}

/// The seven manifest tables of `FORMAT.md` §12.3 and the exact columns each
/// declares, in order.
const MANIFEST_TABLES: &[(&str, &[&str])] = &[
    (
        "baselines.tsv",
        &[
            "baseline_id",
            "established_by_release",
            "parent_baseline_id",
            "introduced_in_corpus_revision",
        ],
    ),
    (
        "diagnostic-classes.tsv",
        &[
            "class_id",
            "description_ref",
            "description_sha3_256",
            "introduced_in_corpus_revision",
        ],
    ),
    (
        "credentials.tsv",
        &[
            "credential_id",
            "kind",
            "primary_ref",
            "primary_sha3_256",
            "secret_ref",
            "secret_sha3_256",
            "introduced_in_release",
            "introduced_in_corpus_revision",
        ],
    ),
    (
        "limit-profiles.tsv",
        &[
            "limit_profile_id",
            "max_header_len",
            "max_recipient_count",
            "max_recipient_body_len",
            "max_header_mac_work_bytes",
            "max_kdf_mem_kib",
            "max_kdf_time",
            "max_kdf_lanes",
            "max_kdf_work",
            "max_recipient_string_chars",
            "max_private_key_wrapped_secret_len",
            "max_entry_count",
            "max_total_plaintext_bytes",
            "max_path_depth",
            "max_path_bytes",
            "max_manifest_bytes",
            "max_archive_ext_bytes",
            "max_entry_ext_bytes",
            "max_total_entry_ext_bytes",
            "max_tlv_value_bytes",
            "introduced_in_corpus_revision",
        ],
    ),
    (
        "origins.tsv",
        &[
            "origin_id",
            "origin_kind",
            "anchor_case_id",
            "payload_key_ref",
            "payload_key_sha3_256",
            "stream_nonce_hex",
            "introduced_in_release",
            "introduced_in_corpus_revision",
        ],
    ),
    (
        "cases.tsv",
        &[
            "case_id",
            "case_type",
            "artifact_ref",
            "artifact_sha3_256",
            "first_required_by_baseline",
            "introduced_in_release",
            "introduced_in_corpus_revision",
            "construction",
            "parent_case_id",
            "payload_transcript_kind",
            "payload_origin_ids",
            "credential_id",
            "limit_profile_id",
            "outcome",
            "expectation_scope",
            "capability_id",
            "condition_id",
            "diagnostic_class",
            "expected_ref",
            "expected_sha3_256",
        ],
    ),
    (
        "errata.tsv",
        &[
            "erratum_id",
            "affected_case_id",
            "effective_corpus_revision",
            "rationale_ref",
            "rationale_sha3_256",
            "replacement_case_id",
            "introduced_in_release",
        ],
    ),
];

/// The columns holding a baseline, class, credential, limit-profile, origin,
/// case, erratum, or condition ID, and whether each may hold `-`. Capability
/// IDs follow the structured forms of `FORMAT.md` §12.2 instead.
const ID_COLUMNS: &[(&str, &[(&str, bool)])] = &[
    (
        "baselines.tsv",
        &[("baseline_id", false), ("parent_baseline_id", true)],
    ),
    ("diagnostic-classes.tsv", &[("class_id", false)]),
    ("credentials.tsv", &[("credential_id", false)]),
    ("limit-profiles.tsv", &[("limit_profile_id", false)]),
    (
        "origins.tsv",
        &[("origin_id", false), ("anchor_case_id", false)],
    ),
    (
        "cases.tsv",
        &[
            ("case_id", false),
            ("first_required_by_baseline", false),
            ("parent_case_id", true),
            ("credential_id", true),
            ("limit_profile_id", true),
            ("condition_id", true),
            ("diagnostic_class", true),
        ],
    ),
    (
        "errata.tsv",
        &[
            ("erratum_id", false),
            ("affected_case_id", false),
            ("replacement_case_id", true),
        ],
    ),
];

type Row = BTreeMap<String, String>;

/// One parsed manifest table, its rows as column-keyed maps.
struct Table {
    rows: Vec<Row>,
}

/// Parses one manifest table strictly: its header must name exactly the
/// columns `FORMAT.md` §12.3 lists, and no field may break a rule
/// [`field_violation`] checks. Every replay reads the manifests through this,
/// so none relies on another test having validated them first.
fn read_table(root: &Path, name: &str) -> Table {
    let expected = MANIFEST_TABLES
        .iter()
        .find(|(table, _)| *table == name)
        .map(|(_, columns)| *columns)
        .unwrap_or_else(|| panic!("{name} is not a §12.3 manifest table"));
    let text = fs::read_to_string(root.join(name)).unwrap_or_else(|e| panic!("read {name}: {e}"));
    assert!(!text.contains('\r'), "{name} must use LF line endings");
    let mut columns: Option<&[&str]> = None;
    let mut rows = Vec::new();
    for line in text.lines() {
        if let Some(header) = line.strip_prefix('#') {
            if columns.is_none() {
                let declared: Vec<&str> = header.trim().split('\t').collect();
                assert_eq!(
                    declared, expected,
                    "{name}: columns differ from FORMAT.md §12.3"
                );
                columns = Some(expected);
            }
            continue;
        }
        let columns = columns.unwrap_or_else(|| panic!("{name}: rows precede the column header"));
        let fields: Vec<&str> = line.split('\t').collect();
        assert_eq!(fields.len(), columns.len(), "{name}: row width");
        for (column, value) in columns.iter().zip(&fields) {
            if let Some(violation) = field_violation(name, column, value) {
                panic!("{name}: {column} {value:?}: {violation}");
            }
        }
        rows.push(
            columns
                .iter()
                .map(|column| column.to_string())
                .zip(fields.iter().map(|value| value.to_string()))
                .collect(),
        );
    }
    assert!(columns.is_some(), "{name}: no column header");
    Table { rows }
}

/// The first `FORMAT.md` §12.3 field rule `value` breaks in `column` of
/// `table`, or `None`: the rules every field shares, then the identifier,
/// reference, digest, list, and capability forms its column carries. `-`
/// stands for an inapplicable value, which an identifier column admits only
/// where it is optional.
fn field_violation(table: &str, column: &str, value: &str) -> Option<&'static str> {
    if value.is_empty() {
        return Some("empty field");
    }
    if value.contains("..") || value.contains('\\') || value.starts_with('/') {
        return Some("contains '..', a backslash, or an absolute path");
    }
    let id_column = ID_COLUMNS
        .iter()
        .find(|(name, _)| *name == table)
        .and_then(|(_, columns)| columns.iter().find(|(name, _)| *name == column));
    if let Some((_, optional)) = id_column {
        let valid = if value == "-" {
            *optional
        } else {
            is_manifest_id(value)
        };
        if !valid {
            return Some("breaks the identifier grammar");
        }
    }
    if table == "limit-profiles.tsv" && column.starts_with("max_") {
        return limit_value_violation(column, value);
    }
    if value == "-" {
        return None;
    }
    if column.ends_with("_ref") && !is_corpus_reference(value) {
        return Some("not a corpus reference");
    }
    if column.ends_with("_sha3_256") && !(value.len() == 64 && is_lower_hex(value)) {
        return Some("not a digest of 64 lowercase hexadecimal characters");
    }
    if column == "payload_origin_ids" {
        let listed: Vec<&str> = value.split(',').collect();
        if !listed.iter().all(|id| is_manifest_id(id)) {
            return Some("breaks the list form");
        }
        if listed.iter().collect::<BTreeSet<_>>().len() != listed.len() {
            return Some("repeats an origin");
        }
    }
    if column == "capability_id" && !is_capability_id(value) {
        return Some("breaks the capability form");
    }
    None
}

fn field<'a>(row: &'a Row, column: &str) -> &'a str {
    row.get(column)
        .unwrap_or_else(|| panic!("missing column {column}"))
}

/// Reads the file `row[ref_column]` names and requires the digest committed
/// in `digest_column`, so a replay run on its own relies on no byte the
/// manifests do not commit. The reference was validated when its table was
/// parsed.
fn read_committed(root: &Path, row: &Row, ref_column: &str, digest_column: &str) -> Vec<u8> {
    let reference = field(row, ref_column);
    assert_ne!(reference, "-", "{ref_column} names no file");
    let bytes = fs::read(root.join(reference)).unwrap_or_else(|e| panic!("read {reference}: {e}"));
    assert_eq!(
        sha3_hex(&bytes),
        field(row, digest_column),
        "{reference} does not match its committed digest"
    );
    bytes
}

/// Collects one column into a set, refusing a repeated value. §12.3 requires
/// replay to reject duplicate IDs rather than let a later row win.
fn unique_ids(table: &Table, name: &str, column: &str) -> BTreeSet<String> {
    let mut seen = BTreeSet::new();
    for row in &table.rows {
        let value = field(row, column).to_string();
        assert!(seen.insert(value.clone()), "{name}: {value}: duplicate id");
    }
    seen
}

/// The corpus revision that appended `row`.
fn introduced_in(row: &Row) -> u32 {
    field(row, "introduced_in_corpus_revision")
        .parse()
        .expect("introduced_in_corpus_revision is a number")
}

/// The revision each row was appended in, which §12.3 bounds by the corpus
/// revision rather than fixing at it: earlier rows stay as later ones arrive.
fn assert_revisions_within(table: &Table, name: &str, revision: u32) {
    for row in &table.rows {
        let introduced = introduced_in(row);
        assert!(introduced >= 1, "{name}: revision 0 does not exist");
        assert!(
            introduced <= revision,
            "{name}: a row from revision {introduced} is ahead of CORPUS-REVISION {revision}"
        );
    }
}

/// Case IDs an erratum withdraws from replay at the current revision. §12.3
/// keeps the row and its history in place; only the replay stops asserting it.
fn cases_withdrawn_by_errata(root: &Path, revision: u32) -> BTreeSet<String> {
    read_table(root, "errata.tsv")
        .rows
        .iter()
        .filter(|row| {
            let effective: u32 = field(row, "effective_corpus_revision")
                .parse()
                .expect("errata.tsv: effective_corpus_revision is not a number");
            effective <= revision
        })
        .map(|row| field(row, "affected_case_id").to_string())
        .collect()
}

fn sha3_hex(bytes: &[u8]) -> String {
    Sha3_256::digest(bytes)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

/// `[a-z0-9][a-z0-9._-]*`
fn is_manifest_id(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first.is_ascii_lowercase() || first.is_ascii_digit())
        && chars
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || matches!(c, '.' | '_' | '-'))
}

/// The rule a `limit-profiles.tsv` value breaks, if any: it is a decimal
/// integer with no leading zero that fits 64 bits, and at most the structural
/// maximum of the quantity it bounds where the format defines one
/// (`FORMAT.md` §12.3), because a reader cannot apply a larger value.
fn limit_value_violation(column: &str, value: &str) -> Option<&'static str> {
    let canonical =
        value == "0" || (!value.starts_with('0') && value.chars().all(|c| c.is_ascii_digit()));
    let Some(limit) = canonical.then(|| value.parse::<u64>().ok()).flatten() else {
        return Some("not a decimal limit that fits 64 bits");
    };
    let structural_max = LIMIT_STRUCTURAL_MAXIMA
        .iter()
        .find(|(name, _)| *name == column)
        .map(|(_, max)| *max);
    if structural_max.is_some_and(|max| limit > max) {
        return Some("above the structural maximum of the quantity it bounds");
    }
    None
}

/// The structural maximum of every profiled quantity the format bounds
/// (`FORMAT.md` §2.2, §3.2, §7, §8, §9.12).
const LIMIT_STRUCTURAL_MAXIMA: &[(&str, u64)] = &[
    (
        "max_header_len",
        HeaderReadLimits::HEADER_LEN_STRUCTURAL_MAX as u64,
    ),
    (
        "max_recipient_count",
        HeaderReadLimits::RECIPIENT_COUNT_STRUCTURAL_MAX as u64,
    ),
    (
        "max_recipient_body_len",
        HeaderReadLimits::RECIPIENT_BODY_LEN_STRUCTURAL_MAX as u64,
    ),
    (
        "max_header_mac_work_bytes",
        HeaderReadLimits::HEADER_MAC_WORK_BYTES_STRUCTURAL_MAX,
    ),
    (
        "max_kdf_mem_kib",
        KdfLimit::MEM_COST_KIB_STRUCTURAL_MAX as u64,
    ),
    ("max_kdf_time", KdfLimit::TIME_COST_STRUCTURAL_MAX as u64),
    ("max_kdf_lanes", KdfLimit::LANES_STRUCTURAL_MAX as u64),
    ("max_kdf_work", KdfLimit::WORK_STRUCTURAL_MAX),
    (
        "max_recipient_string_chars",
        KeyReadLimits::RECIPIENT_STRING_CHARS_STRUCTURAL_MAX as u64,
    ),
    (
        "max_private_key_wrapped_secret_len",
        KeyReadLimits::PRIVATE_KEY_WRAPPED_SECRET_LEN_STRUCTURAL_MAX as u64,
    ),
    (
        "max_path_bytes",
        ArchiveLimits::PATH_BYTES_STRUCTURAL_MAX as u64,
    ),
];

/// A path relative to the corpus root whose components each match the
/// identifier grammar (`FORMAT.md` §12.3). That rules out absolute paths,
/// drive and UNC prefixes, backslashes, and empty, `.`, or `..` components,
/// so joining a reference onto the root can only name a file inside it.
fn is_corpus_reference(value: &str) -> bool {
    value.split('/').all(is_manifest_id)
}

/// The capability-ID forms of `FORMAT.md` §12.2: a stored version domain
/// with two uppercase hexadecimal digits other than the reserved `0x00`, a
/// TLV namespace with four, or a recipient or key type with its name.
fn is_capability_id(value: &str) -> bool {
    let Some((domain, subject)) = value.split_once(':') else {
        return false;
    };
    let hex_digits = |digits: usize| {
        subject.strip_prefix("0x").is_some_and(|hex| {
            hex.len() == digits
                && hex
                    .chars()
                    .all(|c| c.is_ascii_digit() || matches!(c, 'A'..='F'))
        })
    };
    match domain {
        "outer_version" | "fca_version" | "public_key_version" | "private_key_version" => {
            hex_digits(2) && subject != "0x00"
        }
        "outer_tlv" | "private_key_tlv" | "fca_archive_tlv" | "fca_entry_tlv" => hex_digits(4),
        "recipient_type" | "key_type" => !subject.is_empty(),
        _ => false,
    }
}

fn is_lower_hex(value: &str) -> bool {
    value
        .chars()
        .all(|c| c.is_ascii_digit() || matches!(c, 'a'..='f'))
}

/// Maps a typed error to its `FORMAT.md` §12.1 diagnostic class. Structured
/// values only: the corpus contract excludes English display text.
fn diagnostic_class(error: &CryptoError) -> &'static str {
    match error {
        CryptoError::InvalidFormat(defect) => match defect {
            FormatDefect::BadMagic => "bad_magic",
            FormatDefect::Truncated => "truncated",
            FormatDefect::NotAKeyFile => "not_a_key_file",
            FormatDefect::WrongKind { .. } => "wrong_kind",
            FormatDefect::WrongKeyFileType => "wrong_key_file_type",
            FormatDefect::UnsupportedArchiveVersion { .. } => "unsupported_fca_version",
            FormatDefect::OversizedHeader { .. } => "oversized_header",
            FormatDefect::MalformedHeader => "malformed_header",
            FormatDefect::ExtTooLarge { .. } => "extension_region_too_large",
            FormatDefect::MalformedTlv => "malformed_tlv",
            FormatDefect::UnknownCriticalTag { .. } => "unknown_critical_tlv",
            FormatDefect::RecipientCountOutOfRange { .. } => "recipient_count_out_of_range",
            FormatDefect::MalformedTypeName => "malformed_type_name",
            FormatDefect::MalformedRecipientEntry => "malformed_recipient_entry",
            FormatDefect::RecipientFlagsReserved => "recipient_flags_reserved",
            FormatDefect::MalformedPayloadStream => "malformed_payload_stream",
            FormatDefect::MalformedPublicKey => "malformed_public_key",
            FormatDefect::MalformedPrivateKey => "malformed_private_key",
            other => panic!("no diagnostic class mapped for {other:?}"),
        },
        CryptoError::UnsupportedVersion(version) => match version {
            UnsupportedVersion::OlderFile { .. } | UnsupportedVersion::NewerFile { .. } => {
                "unsupported_outer_version"
            }
            UnsupportedVersion::OlderKey { .. } | UnsupportedVersion::NewerKey { .. } => {
                "unsupported_private_key_version"
            }
            UnsupportedVersion::OlderPublicKey { .. }
            | UnsupportedVersion::NewerPublicKey { .. } => "unsupported_public_key_version",
            other => panic!("no diagnostic class mapped for {other:?}"),
        },
        CryptoError::UnknownCriticalRecipient { .. } => "unknown_critical_recipient",
        CryptoError::NoSupportedRecipient => "no_supported_recipient",
        CryptoError::IncompatibleRecipients { .. } => "incompatible_recipients",
        CryptoError::RecipientUnwrapFailed { .. } => "recipient_unwrap_failed",
        CryptoError::HeaderTampered | CryptoError::HeaderMacFailedAfterUnwrap { .. } => {
            "header_authentication_failed"
        }
        CryptoError::InvalidKdfParams(_) => "invalid_kdf_parameters",
        CryptoError::KdfResourceCapExceeded { .. }
        | CryptoError::KdfTimeCostCapExceeded { .. }
        | CryptoError::KdfLanesCapExceeded { .. }
        | CryptoError::KdfWorkCapExceeded { .. }
        | CryptoError::HeaderLenCapExceeded { .. }
        | CryptoError::RecipientCountCapExceeded { .. }
        | CryptoError::RecipientBodyCapExceeded { .. }
        | CryptoError::HeaderMacWorkCapExceeded { .. }
        | CryptoError::RecipientStringCapExceeded { .. }
        | CryptoError::PrivateKeyWrappedSecretCapExceeded { .. }
        | CryptoError::ArchiveEntryCountCapExceeded { .. }
        | CryptoError::ArchiveTotalBytesCapExceeded { .. }
        | CryptoError::ArchiveManifestLenCapExceeded { .. }
        | CryptoError::ArchivePathBytesCapExceeded { .. }
        | CryptoError::ArchivePathDepthCapExceeded { .. }
        | CryptoError::ArchiveExtLenCapExceeded { .. }
        | CryptoError::ArchiveEntryExtLenCapExceeded { .. }
        | CryptoError::ArchiveTotalEntryExtCapExceeded { .. } => "resource_cap_exceeded",
        CryptoError::PayloadTampered => "payload_authentication_failed",
        CryptoError::PayloadTruncated => "payload_truncated",
        // No artifact reaches these two: one needs a reader that yields
        // bytes after reporting the end of the payload, the other a
        // payload of about 281 TB. Mapped so that a reader defect
        // reports a class rather than a panic (`FORMAT.md` §12.1).
        CryptoError::ExtraDataAfterPayload => "extra_data_after_payload",
        CryptoError::PayloadChunkCountExceeded => "payload_chunk_count_exceeded",
        CryptoError::MalformedArchive { .. } => "malformed_archive",
        CryptoError::UnsafeArchivePath { .. } => "unsafe_archive_path",
        CryptoError::InvalidArchiveTree { .. } => "invalid_archive_tree",
        CryptoError::UnsupportedKeyType { .. } => "unsupported_key_type",
        CryptoError::KeyFileUnlockFailed => "private_key_unlock_failed",
        other => panic!("no diagnostic class mapped for {other:?}"),
    }
}

/// A credential resolved from `credentials.tsv`.
enum Credential {
    Passphrase(String),
    PrivateKey { key_path: PathBuf, unlock: String },
    None,
}

/// Resolves every `credentials.tsv` row, keyed by its ID, refusing a
/// duplicate ID. Each committed file is checked against its digest as it is
/// read.
fn read_credentials(root: &Path, table: &Table) -> BTreeMap<String, Credential> {
    let passphrase = |row: &Row, ref_column: &str, digest_column: &str| {
        String::from_utf8(read_committed(root, row, ref_column, digest_column))
            .expect("a passphrase credential is UTF-8")
    };
    let mut credentials = BTreeMap::new();
    for row in &table.rows {
        let (id, credential) = {
            let id = field(row, "credential_id").to_string();
            let credential = match field(row, "kind") {
                "passphrase" => {
                    Credential::Passphrase(passphrase(row, "primary_ref", "primary_sha3_256"))
                }
                "private_key" => {
                    // The API opens the key file by path; its bytes are checked
                    // against the committed digest first.
                    read_committed(root, row, "primary_ref", "primary_sha3_256");
                    Credential::PrivateKey {
                        key_path: root.join(field(row, "primary_ref")),
                        unlock: passphrase(row, "secret_ref", "secret_sha3_256"),
                    }
                }
                "none" => Credential::None,
                other => panic!("{id}: unknown credential kind {other}"),
            };
            (id, credential)
        };
        assert!(
            credentials.insert(id.clone(), credential).is_none(),
            "credentials.tsv: {id}: duplicate id"
        );
    }
    credentials
}

/// One `limit-profiles.tsv` row as the public limit types a replay applies
/// (`FORMAT.md` §12.3).
#[derive(Clone, Copy)]
struct LimitProfile {
    header: HeaderReadLimits,
    kdf: KdfLimit,
    key: KeyReadLimits,
    archive: ArchiveLimits,
}

/// Builds every `limit-profiles.tsv` row, keyed by its ID, refusing a
/// duplicate ID. Each limit type is built in one expression from the
/// profile's own values, so no default survives into a replay, and every
/// limit column must have been read into one of them. A value above a
/// structural maximum was refused when the table was parsed, so no builder
/// clamps what the profile states.
fn read_limit_profiles(table: &Table) -> BTreeMap<String, LimitProfile> {
    let limit_columns: BTreeSet<&str> = MANIFEST_TABLES
        .iter()
        .find(|(name, _)| *name == "limit-profiles.tsv")
        .map(|(_, columns)| columns.iter().copied().filter(|c| c.starts_with("max_")))
        .expect("limit-profiles.tsv is a manifest table")
        .collect();
    let mut profiles = BTreeMap::new();
    for row in &table.rows {
        let id = field(row, "limit_profile_id").to_string();
        let applied = RefCell::new(BTreeSet::new());
        let value = |column: &'static str| -> u64 {
            applied.borrow_mut().insert(column);
            field(row, column)
                .parse()
                .unwrap_or_else(|_| panic!("{id}: {column} is not a decimal limit"))
        };
        let narrow = |column: &'static str| -> u32 {
            u32::try_from(value(column))
                .unwrap_or_else(|_| panic!("{id}: {column} does not fit this build's limit type"))
        };
        let profile = LimitProfile {
            header: HeaderReadLimits::default()
                .max_header_len(narrow("max_header_len"))
                .max_recipient_count(u16::try_from(value("max_recipient_count")).unwrap_or_else(
                    |_| panic!("{id}: max_recipient_count does not fit this build's limit type"),
                ))
                .max_recipient_body_len(narrow("max_recipient_body_len"))
                .max_header_mac_work_bytes(value("max_header_mac_work_bytes")),
            kdf: KdfLimit::new(narrow("max_kdf_mem_kib"))
                .max_time_cost(narrow("max_kdf_time"))
                .max_lanes(narrow("max_kdf_lanes"))
                .max_work(value("max_kdf_work")),
            key: KeyReadLimits::default()
                .max_recipient_string_chars(narrow("max_recipient_string_chars"))
                .max_private_key_wrapped_secret_len(narrow("max_private_key_wrapped_secret_len")),
            archive: ArchiveLimits::default()
                .max_entry_count(narrow("max_entry_count"))
                .max_total_plaintext_bytes(value("max_total_plaintext_bytes"))
                .max_path_depth(narrow("max_path_depth"))
                .max_path_bytes(narrow("max_path_bytes"))
                .max_manifest_bytes(narrow("max_manifest_bytes"))
                .max_archive_ext_bytes(narrow("max_archive_ext_bytes"))
                .max_entry_ext_bytes(narrow("max_entry_ext_bytes"))
                .max_total_entry_ext_bytes(value("max_total_entry_ext_bytes"))
                .max_tlv_value_bytes(narrow("max_tlv_value_bytes")),
        };
        assert_eq!(
            *applied.borrow(),
            limit_columns,
            "{id}: every limit column must reach a limit type"
        );
        assert!(
            profiles.insert(id.clone(), profile).is_none(),
            "limit-profiles.tsv: {id}: duplicate id"
        );
    }
    profiles
}

/// The case types whose action applies no local cap, so their rows name no
/// limit profile (`FORMAT.md` §12.3).
fn applies_no_local_cap(case_type: &str) -> bool {
    matches!(case_type, "private_key_validate" | "stream_encrypt_kat")
}

/// `baseline` and every ancestor `baselines.tsv` records for it.
fn baseline_lineage(root: &Path, baseline: &str) -> BTreeSet<String> {
    let parents: BTreeMap<String, String> = read_table(root, "baselines.tsv")
        .rows
        .iter()
        .map(|row| {
            (
                field(row, "baseline_id").to_string(),
                field(row, "parent_baseline_id").to_string(),
            )
        })
        .collect();
    let mut lineage = BTreeSet::new();
    let mut current = baseline.to_string();
    while current != "-" {
        let parent = parents
            .get(&current)
            .unwrap_or_else(|| panic!("baseline {current} is not declared"))
            .clone();
        assert!(
            lineage.insert(current),
            "the baseline lineage of {baseline} forms a cycle"
        );
        current = parent;
    }
    lineage
}

/// Every `*_ref` column and the `*_sha3_256` column beside it, for the tables
/// that carry them. The payload-key commitment is excluded: §12.3 defines it
/// as a digest of key material rather than of a referenced file.
const DIGEST_PAIRS: &[(&str, &[(&str, &str)])] = &[
    (
        "diagnostic-classes.tsv",
        &[("description_ref", "description_sha3_256")],
    ),
    (
        "credentials.tsv",
        &[
            ("primary_ref", "primary_sha3_256"),
            ("secret_ref", "secret_sha3_256"),
        ],
    ),
    (
        "cases.tsv",
        &[
            ("artifact_ref", "artifact_sha3_256"),
            ("expected_ref", "expected_sha3_256"),
        ],
    ),
    ("errata.tsv", &[("rationale_ref", "rationale_sha3_256")]),
];

/// Every reference column, `origins.tsv`'s `payload_key_ref` included, admits
/// a corpus path and refuses every form that could name a file outside the
/// corpus, or a different file on another platform, before a replay reads it
/// (`FORMAT.md` §12.3).
#[test]
fn every_reference_column_refuses_paths_outside_the_corpus() {
    let refused = [
        "/etc/passwd",
        "../outside",
        "a/../b",
        "a/./b",
        "./a",
        "a//b",
        "a/",
        "C:/outside",
        "C:outside",
        "a\\b",
        "\\\\server\\share",
        "Artifacts/a",
        "a/b c",
    ];
    let mut checked = 0;
    for (table, columns) in MANIFEST_TABLES {
        for column in columns.iter().filter(|column| column.ends_with("_ref")) {
            assert_eq!(
                field_violation(table, column, "artifacts/fcr/case-1.fcr"),
                None
            );
            for reference in refused {
                assert!(
                    field_violation(table, column, reference).is_some(),
                    "{table}: {column} admits {reference:?}"
                );
            }
            checked += 1;
        }
    }
    assert_eq!(checked, 7, "every reference column of the seven tables");
}

/// Every identifier column enforces the identifier grammar, and a required one
/// refuses `-` (`FORMAT.md` §12.3). Each column named here exists in its
/// table, so a renamed column cannot silently drop out of the check.
#[test]
fn every_identifier_column_enforces_the_identifier_grammar() {
    for (table, columns) in ID_COLUMNS {
        let declared = MANIFEST_TABLES
            .iter()
            .find(|(name, _)| name == table)
            .map(|(_, declared)| *declared)
            .unwrap_or_else(|| panic!("{table} is not a manifest table"));
        for (column, optional) in *columns {
            assert!(declared.contains(column), "{table} has no {column} column");
            assert_eq!(field_violation(table, column, "valid.id_1-2"), None);
            for invalid in ["Upper", "-leading", ".leading", "with space", "a,b"] {
                assert!(
                    field_violation(table, column, invalid).is_some(),
                    "{table}: {column} admits {invalid:?}"
                );
            }
            assert_eq!(
                field_violation(table, column, "-").is_none(),
                *optional,
                "{table}: {column} decides '-' by whether the column is optional"
            );
        }
    }
}

/// Every limit column holds a decimal value a reader can apply as stated: no
/// sign, leading zero, or `-`, nothing beyond 64 bits, and nothing above the
/// structural maximum of the quantity it bounds, which a reader would clamp
/// (`FORMAT.md` §12.3).
#[test]
fn every_limit_column_holds_a_value_a_reader_can_apply() {
    let profile_columns = MANIFEST_TABLES
        .iter()
        .find(|(table, _)| *table == "limit-profiles.tsv")
        .map(|(_, columns)| *columns)
        .expect("limit-profiles.tsv is a manifest table");
    fn limit(column: &str, value: &str) -> Option<&'static str> {
        field_violation("limit-profiles.tsv", column, value)
    }
    for column in profile_columns.iter().filter(|c| c.starts_with("max_")) {
        assert_eq!(limit(column, "0"), None, "{column}");
        for invalid in ["-", "01", "+1", "1.0", "0x10", "18446744073709551616"] {
            assert!(
                limit(column, invalid).is_some(),
                "{column} admits {invalid:?}"
            );
        }
    }
    for (column, max) in LIMIT_STRUCTURAL_MAXIMA {
        assert!(profile_columns.contains(column), "no {column} column");
        assert_eq!(limit(column, &max.to_string()), None, "{column}");
        assert!(
            limit(column, &(max + 1).to_string()).is_some(),
            "{column} admits a value above its structural maximum"
        );
    }
}

/// A table whose header names other columns than `FORMAT.md` §12.3 lists is
/// a different schema, refused before any of its rows is read.
#[test]
#[should_panic(expected = "columns differ from FORMAT.md §12.3")]
fn a_table_with_other_columns_is_refused() {
    let dir = tempfile::tempdir().expect("table dir");
    fs::write(
        dir.path().join("baselines.tsv"),
        "# baseline_id\testablished_by_release\tparent_baseline_id\tintroduced_in_corpus_revision\textra\n",
    )
    .expect("write table");
    read_table(dir.path(), "baselines.tsv");
}

/// The origin list and the capability column hold the forms `FORMAT.md`
/// §12.2 and §12.3 define, and nothing else.
#[test]
fn list_and_capability_columns_hold_their_forms() {
    let list = |value| field_violation("cases.tsv", "payload_origin_ids", value);
    assert_eq!(list("origin-a,origin-b"), None);
    for invalid in [
        "origin-a,",
        ",origin-a",
        "origin-a, origin-b",
        "origin-a,origin-a",
    ] {
        assert!(
            list(invalid).is_some(),
            "the origin list admits {invalid:?}"
        );
    }

    let capability = |value| field_violation("cases.tsv", "capability_id", value);
    for valid in [
        "outer_version:0x02",
        "private_key_version:0xFF",
        "fca_entry_tlv:0x8001",
        "recipient_type:test/unknown",
        "key_type:test/unknown",
    ] {
        assert_eq!(capability(valid), None, "{valid:?}");
    }
    for invalid in [
        "outer_version:0x00",
        "outer_version:0x2",
        "outer_version:0x0a",
        "outer_tlv:0x001",
        "fca_version:02",
        "recipient_type:",
        "unknown_domain:0x01",
        "outer_version",
    ] {
        assert!(
            capability(invalid).is_some(),
            "the capability column admits {invalid:?}"
        );
    }
}

#[test]
fn wire_corpus_manifests_are_well_formed() {
    if !corpus_present() {
        return;
    }
    let root = corpus_root();
    assert_eq!(
        fs::read_to_string(root.join("SCHEMA-VERSION"))
            .expect("read SCHEMA-VERSION")
            .trim(),
        "1"
    );
    let revision: u32 = fs::read_to_string(root.join("CORPUS-REVISION"))
        .expect("read CORPUS-REVISION")
        .trim()
        .parse()
        .expect("CORPUS-REVISION is a number");
    assert!(revision >= 1, "revision 0 does not exist");

    // Every committed digest must equal the digest of the bytes its reference
    // names, so a row can never describe a file the corpus does not hold.
    for (table_name, pairs) in DIGEST_PAIRS {
        for row in read_table(&root, table_name).rows {
            for (ref_column, digest_column) in *pairs {
                if field(&row, ref_column) == "-" {
                    assert_eq!(
                        field(&row, digest_column),
                        "-",
                        "{table_name}: '-' reference needs a '-' digest"
                    );
                    continue;
                }
                read_committed(&root, &row, ref_column, digest_column);
            }
        }
    }

    // The initial baseline row FORMAT.md §12.3 fixes for revision 1.
    let baselines = read_table(&root, "baselines.tsv");
    assert_eq!(baselines.rows.len(), 1, "revision 1 declares one baseline");
    let baseline = &baselines.rows[0];
    assert_eq!(field(baseline, "baseline_id"), "0.3.0");
    assert_eq!(field(baseline, "established_by_release"), "0.3.0");
    assert_eq!(field(baseline, "parent_baseline_id"), "-");

    let class_table = read_table(&root, "diagnostic-classes.tsv");
    let credential_table = read_table(&root, "credentials.tsv");
    let origin_table = read_table(&root, "origins.tsv");
    let case_table = read_table(&root, "cases.tsv");
    let errata_table = read_table(&root, "errata.tsv");
    let profile_table = read_table(&root, "limit-profiles.tsv");

    // Every identifier is declared once, and every row was appended by this
    // revision or an earlier one. The credential and profile readers refuse
    // a duplicate ID themselves; building the profiles also checks that every
    // value reaches a limit type.
    let credentials = read_credentials(&root, &credential_table);
    read_limit_profiles(&profile_table);
    let classes = unique_ids(&class_table, "diagnostic-classes.tsv", "class_id");
    let origins = unique_ids(&origin_table, "origins.tsv", "origin_id");
    let case_ids = unique_ids(&case_table, "cases.tsv", "case_id");
    unique_ids(&errata_table, "errata.tsv", "erratum_id");
    for (name, table) in [
        ("baselines.tsv", &baselines),
        ("diagnostic-classes.tsv", &class_table),
        ("credentials.tsv", &credential_table),
        ("limit-profiles.tsv", &profile_table),
        ("origins.tsv", &origin_table),
        ("cases.tsv", &case_table),
    ] {
        assert_revisions_within(table, name, revision);
    }

    // A case names only a baseline or a limit profile declared by its own
    // revision or an earlier one.
    let declared_in = |table: &Table, id_column: &str| -> BTreeMap<String, u32> {
        table
            .rows
            .iter()
            .map(|row| (field(row, id_column).to_string(), introduced_in(row)))
            .collect()
    };
    let baseline_revisions = declared_in(&baselines, "baseline_id");
    let profile_revisions = declared_in(&profile_table, "limit_profile_id");
    let mut profiles_named = BTreeSet::new();

    for row in &case_table.rows {
        let case_id = field(row, "case_id");
        let case_revision = introduced_in(row);
        let baseline = field(row, "first_required_by_baseline");
        let baseline_revision = baseline_revisions
            .get(baseline)
            .unwrap_or_else(|| panic!("{case_id}: baseline {baseline} undeclared"));
        assert!(
            *baseline_revision <= case_revision,
            "{case_id}: first required by a baseline declared after the case"
        );
        let profile = field(row, "limit_profile_id");
        if applies_no_local_cap(field(row, "case_type")) {
            assert_eq!(profile, "-", "{case_id}: its action applies no local cap");
        } else {
            let profile_revision = profile_revisions
                .get(profile)
                .unwrap_or_else(|| panic!("{case_id}: limit profile {profile} undeclared"));
            assert!(
                *profile_revision <= case_revision,
                "{case_id}: names a limit profile declared after the case"
            );
            profiles_named.insert(profile.to_string());
        }

        let outcome = field(row, "outcome");
        let class = field(row, "diagnostic_class");
        let condition = field(row, "condition_id");
        let expected = field(row, "expected_ref");
        match outcome {
            "reject" => {
                assert_ne!(condition, "-", "{case_id}: reject needs a condition");
                assert!(
                    classes.contains(class),
                    "{case_id}: class {class} undeclared"
                );
                assert_eq!(
                    expected, "-",
                    "{case_id}: reject carries no expected result"
                );
            }
            "accept" | "transcript_equal" => {
                assert_ne!(
                    expected, "-",
                    "{case_id}: non-reject needs an expected result"
                );
                assert_eq!(class, "-", "{case_id}: non-reject uses class '-'");
            }
            other => panic!("{case_id}: unknown outcome {other}"),
        }

        match field(row, "expectation_scope") {
            "invariant" => assert_eq!(field(row, "capability_id"), "-"),
            "capability_relative" => assert_ne!(field(row, "capability_id"), "-"),
            other => panic!("{case_id}: unknown expectation scope {other}"),
        }

        let transcript = field(row, "payload_transcript_kind");
        if field(row, "case_type") == "fcr_decrypt" {
            assert!(
                matches!(transcript, "origins" | "none"),
                "{case_id}: transcript kind"
            );
        } else {
            assert_eq!(transcript, "not_applicable", "{case_id}: transcript kind");
        }
        if transcript == "origins" {
            for origin in field(row, "payload_origin_ids").split(',') {
                assert!(
                    origins.contains(origin),
                    "{case_id}: origin {origin} undeclared"
                );
            }
        } else {
            assert_eq!(
                field(row, "payload_origin_ids"),
                "-",
                "{case_id}: origins list"
            );
        }

        if field(row, "construction") == "mutation" {
            assert_ne!(
                field(row, "parent_case_id"),
                "-",
                "{case_id}: mutation parent"
            );
        } else {
            assert_eq!(
                field(row, "parent_case_id"),
                "-",
                "{case_id}: parent only for mutations"
            );
        }

        let credential = field(row, "credential_id");
        if credential != "-" {
            assert!(
                credentials.contains_key(credential),
                "{case_id}: credential undeclared"
            );
        }
    }

    // Every origin's anchor case exists, every origin commits to its payload
    // key, a KAT origin names the key file behind that commitment, and
    // independent origins use distinct nonce prefixes.
    let mut nonces = BTreeSet::new();
    for row in &origin_table.rows {
        let origin_id = field(row, "origin_id");
        assert!(
            case_ids.contains(field(row, "anchor_case_id")),
            "{origin_id}: anchor case is not declared"
        );
        match field(row, "origin_kind") {
            "stream_kat" => assert_ne!(
                field(row, "payload_key_ref"),
                "-",
                "{origin_id}: a KAT origin names its payload key"
            ),
            "fcr_payload" => {}
            other => panic!("{origin_id}: unknown origin kind {other}"),
        }
        assert_ne!(
            field(row, "payload_key_sha3_256"),
            "-",
            "{origin_id}: an origin commits to its payload key"
        );
        if field(row, "payload_key_ref") != "-" {
            read_committed(&root, row, "payload_key_ref", "payload_key_sha3_256");
        }
        let nonce = field(row, "stream_nonce_hex");
        assert!(
            nonce.len() == 38 && is_lower_hex(nonce),
            "{origin_id}: stream_nonce_hex is a 19-byte prefix in lowercase hexadecimal"
        );
        assert!(
            nonces.insert(nonce.to_string()),
            "{origin_id}: duplicate nonce prefix"
        );
    }

    // An erratum names an existing case, states a rationale, and takes effect
    // from a revision. §12.3 keeps the affected row and its history in place.
    for row in &errata_table.rows {
        let erratum_id = field(row, "erratum_id");
        assert!(
            case_ids.contains(field(row, "affected_case_id")),
            "{erratum_id}: affected case is not declared"
        );
        let replacement = field(row, "replacement_case_id");
        assert!(
            replacement == "-" || case_ids.contains(replacement),
            "{erratum_id}: replacement case is not declared"
        );
        assert_ne!(
            field(row, "rationale_ref"),
            "-",
            "{erratum_id}: an erratum states its rationale"
        );
        let effective: u32 = field(row, "effective_corpus_revision")
            .parse()
            .unwrap_or_else(|_| panic!("{erratum_id}: effective_corpus_revision is not a number"));
        assert!(effective >= 1, "{erratum_id}: revision 0 does not exist");
    }

    // A profile no case names is configuration nothing is evaluated under.
    for profile in profile_revisions.keys() {
        assert!(
            profiles_named.contains(profile),
            "limit-profiles.tsv: {profile}: no case names this profile"
        );
    }

    assert_every_file_is_referenced(&root, &origin_table);
}

/// Whether a corpus-relative path carries the corpus rather than being carried
/// by it, so no manifest row names it. A rule rather than a list of names:
/// `tools/` is matched by prefix, so adding a tool needs no edit here nor in
/// the two other checkers that apply the same rule.
fn is_structural_corpus_file(relative: &str) -> bool {
    MANIFEST_TABLES.iter().any(|(table, _)| *table == relative)
        || matches!(relative, "SCHEMA-VERSION" | "CORPUS-REVISION" | "README.md")
        || relative.starts_with("tools/")
}

/// Every other file must be reachable from a manifest row. The corpus is
/// frozen and append-only, so a file no row names would be committed forever
/// with no digest behind it and no way to notice a change.
fn assert_every_file_is_referenced(root: &Path, origins: &Table) {
    let mut referenced = BTreeSet::new();
    for (table_name, pairs) in DIGEST_PAIRS {
        for row in read_table(root, table_name).rows {
            for (ref_column, _) in *pairs {
                let reference = field(&row, ref_column);
                if reference != "-" {
                    referenced.insert(reference.to_string());
                }
            }
        }
    }
    for row in &origins.rows {
        let reference = field(row, "payload_key_ref");
        if reference != "-" {
            referenced.insert(reference.to_string());
        }
    }

    for path in walk_files(root) {
        let relative = path
            .strip_prefix(root)
            .expect("corpus file is under the corpus root")
            .to_str()
            .expect("corpus path is UTF-8")
            .replace('\\', "/");
        assert!(
            is_structural_corpus_file(&relative) || referenced.contains(&relative),
            "{relative}: no manifest row references this file"
        );
    }
}

/// Every file under `root`, recursively.
fn walk_files(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir).expect("read corpus directory") {
            let path = entry.expect("read corpus entry").path();
            if path.is_dir() {
                stack.push(path);
            } else {
                out.push(path);
            }
        }
    }
    out
}

#[test]
fn wire_corpus_cases_replay() {
    if !corpus_present() {
        return;
    }
    let root = corpus_root();
    let credentials = read_credentials(&root, &read_table(&root, "credentials.tsv"));
    let profiles = read_limit_profiles(&read_table(&root, "limit-profiles.tsv"));
    let claimed_baselines = baseline_lineage(&root, CLAIMED_BASELINE);
    let revision: u32 = fs::read_to_string(root.join("CORPUS-REVISION"))
        .expect("read CORPUS-REVISION")
        .trim()
        .parse()
        .expect("CORPUS-REVISION is a number");
    let withdrawn = cases_withdrawn_by_errata(&root, revision);
    let case_table = read_table(&root, "cases.tsv");
    // Every row lands in exactly one of these buckets. Counting them all is
    // what turns "some cases ran" into "no case row went unasserted".
    let mut replayed = 0usize;
    let mut deferred_to_kat_replay = 0usize;
    let mut withdrawn_by_errata = 0usize;
    let mut skipped_as_declared = 0usize;

    for row in &case_table.rows {
        let case_id = field(row, "case_id");
        let baseline = field(row, "first_required_by_baseline");
        assert!(
            claimed_baselines.contains(baseline),
            "{case_id}: first required by baseline {baseline}, which this build does not claim"
        );
        // §12.3: an erratum stops the replay asserting its case from the
        // revision it takes effect in; the row itself is never removed.
        if withdrawn.contains(case_id) {
            withdrawn_by_errata += 1;
            continue;
        }
        let capability = field(row, "capability_id");
        // §12.2: assert the stored outcome unless this build declares the
        // capability the case depends on.
        if capability != "-" && DECLARED_CAPABILITIES.contains(&capability) {
            skipped_as_declared += 1;
            continue;
        }
        // The API reads the artifact by path; its bytes are checked against
        // the committed digest first.
        read_committed(&root, row, "artifact_ref", "artifact_sha3_256");
        let artifact = root.join(field(row, "artifact_ref"));
        let credential = credentials
            .get(field(row, "credential_id"))
            .unwrap_or_else(|| panic!("{case_id}: credential not declared"));
        let case_type = field(row, "case_type");
        let profile_id = field(row, "limit_profile_id");
        assert_eq!(
            profile_id == "-",
            applies_no_local_cap(case_type),
            "{case_id}: names a limit profile exactly when its action applies local caps"
        );
        // §12.3: every local cap is set to the profile's value, whatever the
        // case expects.
        let limits = || {
            *profiles
                .get(profile_id)
                .unwrap_or_else(|| panic!("{case_id}: limit profile {profile_id} undeclared"))
        };
        let out = tempfile::tempdir().expect("replay output dir");
        // Each arm returns the byte-exact record the corpus commits for an
        // accepted case, so acceptance proves what was produced rather than
        // only that the operation succeeded.
        let result = match case_type {
            "fcr_decrypt" => {
                decrypt_case(&artifact, credential, limits(), out.path()).map(|path| {
                    // §12.3: the extracted root kind chooses the comparison. A file
                    // root is compared as content; a directory root has no single
                    // plaintext, so it is compared as an extraction listing.
                    if path.is_dir() {
                        extraction_listing(&path)
                    } else {
                        fs::read(path).expect("read decrypted output")
                    }
                })
            }
            "public_key_decode" => PublicKey::from_key_file_with_limits(&artifact, limits().key)
                .and_then(|key| key.to_x25519_bytes())
                .map(|material| material.to_vec()),
            "private_key_validate" => validate_private_key_file(&artifact).map(|()| Vec::new()),
            "private_key_open" => {
                let Credential::PrivateKey { unlock, .. } = credential else {
                    panic!("{case_id}: a private_key_open case needs a private-key credential")
                };
                let limits = limits();
                PrivateKey::from_key_file(&artifact, Passphrase::new(unlock.clone()))
                    .into_public_key_with_limits(limits.kdf, limits.key, ignore_progress)
                    .and_then(|key| key.to_x25519_bytes())
                    .map(|material| material.to_vec())
            }
            // Raw STREAM encryption is not public API, so the known-answer
            // cases are replayed by the library's own `replay_stream_kats`
            // unit test rather than from here.
            "stream_encrypt_kat" => {
                deferred_to_kat_replay += 1;
                continue;
            }
            other => panic!("{case_id}: replay does not cover case type {other}"),
        };

        match field(row, "outcome") {
            "accept" => {
                let produced =
                    result.unwrap_or_else(|e| panic!("{case_id}: must be accepted, got {e:?}"));
                let expected = read_committed(&root, row, "expected_ref", "expected_sha3_256");
                assert_eq!(
                    produced, expected,
                    "{case_id}: result differs from the committed expectation"
                );
            }
            "reject" => {
                let error = result.expect_err(&format!("{case_id}: must be rejected"));
                assert_eq!(
                    diagnostic_class(&error),
                    field(row, "diagnostic_class"),
                    "{case_id}: rejected with the wrong diagnostic class ({error:?})"
                );
            }
            other => panic!("{case_id}: unexpected outcome {other}"),
        }
        replayed += 1;
    }

    // Accounting, not a floor. A row that reaches none of the four buckets —
    // a `continue` added without one, a filter that drops rows — fails here
    // instead of going quietly unasserted.
    let accounted = replayed + deferred_to_kat_replay + withdrawn_by_errata + skipped_as_declared;
    assert_eq!(
        accounted,
        case_table.rows.len(),
        "every case row must be replayed or skipped for a reason §12.2 or §12.3 states"
    );
    // Only the STREAM known-answer rows may be deferred: raw payload
    // encryption is crate-internal, so `replay_stream_kats` covers exactly
    // this set and asserts the same count from its side. A row already
    // withdrawn or skipped above is owed to neither half, so it is not
    // counted here either.
    let stream_rows = case_table
        .rows
        .iter()
        .filter(|row| field(row, "case_type") == "stream_encrypt_kat")
        .filter(|row| !withdrawn.contains(field(row, "case_id")))
        .filter(|row| {
            let capability = field(row, "capability_id");
            capability == "-" || !DECLARED_CAPABILITIES.contains(&capability)
        })
        .count();
    assert_eq!(
        deferred_to_kat_replay, stream_rows,
        "only STREAM known-answer rows may be deferred to the crate-internal replay"
    );
    assert!(replayed > 0, "the corpus replayed no cases");
    println!(
        "wire corpus: {} case row(s) — {replayed} replayed here, {deferred_to_kat_replay} deferred to replay_stream_kats, {withdrawn_by_errata} withdrawn by errata, {skipped_as_declared} skipped as declared capabilities",
        case_table.rows.len()
    );
}

/// Builds the extraction listing `FORMAT.md` §12.3 defines for a directory
/// root: one line per extracted object, ordered by path depth and then by path
/// bytes, holding kind, size, content digest, and the archive path.
fn extraction_listing(root: &Path) -> Vec<u8> {
    let root_name = root
        .file_name()
        .expect("extracted root has a name")
        .to_str()
        .expect("extracted root name is UTF-8")
        .to_string();
    let mut objects = Vec::new();
    collect_objects(root, &root_name, &mut objects);
    objects.sort_by(|(a, _), (b, _)| {
        a.split('/')
            .count()
            .cmp(&b.split('/').count())
            .then_with(|| a.cmp(b))
    });
    let mut out = String::new();
    for (path, content) in objects {
        match content {
            Some(bytes) => {
                out.push_str(&format!("f {} {} {path}\n", bytes.len(), sha3_hex(&bytes)))
            }
            None => out.push_str(&format!("d - - {path}\n")),
        }
    }
    out.into_bytes()
}

/// Walks an extracted tree, pairing each archive path with its file content,
/// or with `None` for a directory. Recursion is bounded by the FCA path-depth
/// cap the extraction already enforced.
fn collect_objects(path: &Path, archive_path: &str, out: &mut Vec<(String, Option<Vec<u8>>)>) {
    if path.is_dir() {
        out.push((archive_path.to_string(), None));
        let mut children: Vec<PathBuf> = fs::read_dir(path)
            .expect("read extracted directory")
            .map(|entry| entry.expect("read directory entry").path())
            .collect();
        children.sort();
        for child in children {
            let name = child
                .file_name()
                .expect("extracted entry has a name")
                .to_str()
                .expect("extracted entry name is UTF-8")
                .to_string();
            collect_objects(&child, &format!("{archive_path}/{name}"), out);
        }
    } else {
        out.push((
            archive_path.to_string(),
            Some(fs::read(path).expect("read extracted file")),
        ));
    }
}

/// Named rather than a closure: a `&|_| {}` literal infers a single concrete
/// lifetime, which does not satisfy the callback's higher-ranked bound.
fn ignore_progress(_event: &ProgressEvent) {}

/// Decrypts `artifact` with every local cap set from `limits`: the header
/// caps from the open onward, and the KDF, key-file, and archive caps for the
/// decryption and any private-key unlock it performs.
fn decrypt_case(
    artifact: &Path,
    credential: &Credential,
    limits: LimitProfile,
    out: &Path,
) -> Result<PathBuf, CryptoError> {
    match (
        Decryptor::open_with_limits(artifact, limits.header)?,
        credential,
    ) {
        (Decryptor::Passphrase(decryptor), Credential::Passphrase(text)) => decryptor
            .kdf_limit(limits.kdf)
            .archive_limits(limits.archive)
            .decrypt(Passphrase::new(text.clone()), out, ignore_progress)
            .map(|outcome| outcome.output_path),
        (Decryptor::PrivateKey(decryptor), Credential::PrivateKey { key_path, unlock }) => {
            decryptor
                .kdf_limit(limits.kdf)
                .key_read_limits(limits.key)
                .archive_limits(limits.archive)
                .decrypt(
                    PrivateKey::from_key_file(key_path, Passphrase::new(unlock.clone())),
                    out,
                    ignore_progress,
                )
                .map(|outcome| outcome.output_path)
        }
        (opened, _) => panic!("credential does not match the classified mode {opened:?}"),
    }
}
