//! Replays the frozen `testvectors/wire/` conformance corpus (`FORMAT.md`
//! §12.3) through the public API.
//!
//! This is FerroCrypt's own replay layer for the corpus it publishes. It
//! validates the manifest grammar and referential integrity, checks every
//! committed digest against the bytes it names, and then asserts each case's
//! recorded outcome. Per §12.1 the assertion maps typed [`CryptoError`] values
//! to stable diagnostic-class identifiers; it never parses English display
//! text, because that text is not part of the cross-language contract.
//!
//! The corpus is regenerated by the ignored `wire_vector_gen` unit test in the
//! library crate and committed by hand.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use ferrocrypt::{
    CryptoError, Decryptor, FormatDefect, Passphrase, PrivateKey, ProgressEvent, PublicKey,
    UnsupportedVersion, validate_private_key_file,
};
use sha3::{Digest, Sha3_256};

/// Capabilities this build supports beyond the `0.3.0` baseline. A
/// capability-relative case is asserted only while its capability is absent
/// (`FORMAT.md` §12.2); FerroCrypt implements none of the future versions and
/// types the corpus names, so the set is empty and every stored outcome is
/// asserted.
const DECLARED_CAPABILITIES: &[&str] = &[];

fn corpus_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("testvectors/wire")
}

/// Whether the corpus is on disk at all. `Cargo.toml` excludes it from the
/// published crate, so these replays skip there; a checkout always has the
/// directory, and a file missing from inside it still fails loudly below. A
/// corpus deleted from a checkout is caught by `tools/verify_manifests.py`,
/// which CI runs as a job of its own.
fn corpus_present() -> bool {
    corpus_root().is_dir()
}

/// One parsed manifest table: the column names from the header comment, and
/// the rows as column-keyed maps.
struct Table {
    rows: Vec<BTreeMap<String, String>>,
}

fn read_table(root: &Path, name: &str) -> Table {
    let text = fs::read_to_string(root.join(name)).unwrap_or_else(|e| panic!("read {name}: {e}"));
    assert!(!text.contains('\r'), "{name} must use LF line endings");
    let mut columns: Option<Vec<String>> = None;
    let mut rows = Vec::new();
    for line in text.lines() {
        if let Some(header) = line.strip_prefix('#') {
            if columns.is_none() {
                columns = Some(header.trim().split('\t').map(str::to_string).collect());
            }
            continue;
        }
        let columns = columns
            .as_ref()
            .unwrap_or_else(|| panic!("{name}: rows precede the column header"));
        let fields: Vec<&str> = line.split('\t').collect();
        assert_eq!(fields.len(), columns.len(), "{name}: row width");
        rows.push(
            columns
                .iter()
                .cloned()
                .zip(fields.iter().map(|f| f.to_string()))
                .collect(),
        );
    }
    Table { rows }
}

fn field<'a>(row: &'a BTreeMap<String, String>, column: &str) -> &'a str {
    row.get(column)
        .unwrap_or_else(|| panic!("missing column {column}"))
}

/// Collects one column into a set, refusing a repeated value. §12.3 requires
/// replay to reject duplicate IDs rather than let a later row win.
fn unique_ids(table: &Table, name: &str, column: &str) -> BTreeSet<String> {
    let mut seen = BTreeSet::new();
    for row in &table.rows {
        let value = field(row, column).to_string();
        assert!(seen.insert(value.clone()), "{name}: {value}: duplicate id");
    }
    seen
}

/// The revision each row was appended in, which §12.3 bounds by the corpus
/// revision rather than fixing at it: earlier rows stay as later ones arrive.
fn assert_revisions_within(table: &Table, name: &str, revision: u32) {
    for row in &table.rows {
        let introduced: u32 = field(row, "introduced_in_corpus_revision")
            .parse()
            .unwrap_or_else(|_| panic!("{name}: introduced_in_corpus_revision is not a number"));
        assert!(introduced >= 1, "{name}: revision 0 does not exist");
        assert!(
            introduced <= revision,
            "{name}: a row from revision {introduced} is ahead of CORPUS-REVISION {revision}"
        );
    }
}

/// Case IDs an erratum withdraws from replay at the current revision. §12.3
/// keeps the row and its history in place; only the replay stops asserting it.
fn cases_withdrawn_by_errata(root: &Path, revision: u32) -> BTreeSet<String> {
    read_table(root, "errata.tsv")
        .rows
        .iter()
        .filter(|row| {
            let effective: u32 = field(row, "effective_corpus_revision")
                .parse()
                .expect("errata.tsv: effective_corpus_revision is not a number");
            effective <= revision
        })
        .map(|row| field(row, "affected_case_id").to_string())
        .collect()
}

fn sha3_hex(bytes: &[u8]) -> String {
    Sha3_256::digest(bytes)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

/// `[a-z0-9][a-z0-9._-]*`
fn is_manifest_id(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first.is_ascii_lowercase() || first.is_ascii_digit())
        && chars
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || matches!(c, '.' | '_' | '-'))
}

/// Maps a typed error to its `FORMAT.md` §12.1 diagnostic class. Structured
/// values only: the corpus contract excludes English display text.
fn diagnostic_class(error: &CryptoError) -> &'static str {
    match error {
        CryptoError::InvalidFormat(defect) => match defect {
            FormatDefect::BadMagic => "bad_magic",
            FormatDefect::Truncated => "truncated",
            FormatDefect::NotAKeyFile => "not_a_key_file",
            FormatDefect::WrongKind { .. } => "wrong_kind",
            FormatDefect::WrongKeyFileType => "wrong_key_file_type",
            FormatDefect::UnsupportedArchiveVersion { .. } => "unsupported_fca_version",
            FormatDefect::OversizedHeader { .. } => "oversized_header",
            FormatDefect::MalformedHeader => "malformed_header",
            FormatDefect::ExtTooLarge { .. } => "extension_region_too_large",
            FormatDefect::MalformedTlv => "malformed_tlv",
            FormatDefect::UnknownCriticalTag { .. } => "unknown_critical_tlv",
            FormatDefect::RecipientCountOutOfRange { .. } => "recipient_count_out_of_range",
            FormatDefect::MalformedTypeName => "malformed_type_name",
            FormatDefect::MalformedRecipientEntry => "malformed_recipient_entry",
            FormatDefect::RecipientFlagsReserved => "recipient_flags_reserved",
            FormatDefect::MalformedPayloadStream => "malformed_payload_stream",
            FormatDefect::MalformedPublicKey => "malformed_public_key",
            FormatDefect::MalformedPrivateKey => "malformed_private_key",
            other => panic!("no diagnostic class mapped for {other:?}"),
        },
        CryptoError::UnsupportedVersion(version) => match version {
            UnsupportedVersion::OlderFile { .. } | UnsupportedVersion::NewerFile { .. } => {
                "unsupported_outer_version"
            }
            UnsupportedVersion::OlderKey { .. } | UnsupportedVersion::NewerKey { .. } => {
                "unsupported_private_key_version"
            }
            UnsupportedVersion::OlderPublicKey { .. }
            | UnsupportedVersion::NewerPublicKey { .. } => "unsupported_public_key_version",
            other => panic!("no diagnostic class mapped for {other:?}"),
        },
        CryptoError::UnknownCriticalRecipient { .. } => "unknown_critical_recipient",
        CryptoError::NoSupportedRecipient => "no_supported_recipient",
        CryptoError::IncompatibleRecipients { .. } => "incompatible_recipients",
        CryptoError::RecipientUnwrapFailed { .. } => "recipient_unwrap_failed",
        CryptoError::HeaderTampered | CryptoError::HeaderMacFailedAfterUnwrap { .. } => {
            "header_authentication_failed"
        }
        CryptoError::InvalidKdfParams(_) => "invalid_kdf_parameters",
        CryptoError::KdfResourceCapExceeded { .. }
        | CryptoError::KdfTimeCostCapExceeded { .. }
        | CryptoError::KdfLanesCapExceeded { .. }
        | CryptoError::KdfWorkCapExceeded { .. }
        | CryptoError::HeaderLenCapExceeded { .. }
        | CryptoError::RecipientCountCapExceeded { .. }
        | CryptoError::RecipientBodyCapExceeded { .. }
        | CryptoError::HeaderMacWorkCapExceeded { .. }
        | CryptoError::RecipientStringCapExceeded { .. }
        | CryptoError::PrivateKeyWrappedSecretCapExceeded { .. }
        | CryptoError::ArchiveEntryCountCapExceeded { .. }
        | CryptoError::ArchiveTotalBytesCapExceeded { .. }
        | CryptoError::ArchiveManifestLenCapExceeded { .. }
        | CryptoError::ArchivePathBytesCapExceeded { .. }
        | CryptoError::ArchivePathDepthCapExceeded { .. }
        | CryptoError::ArchiveExtLenCapExceeded { .. }
        | CryptoError::ArchiveEntryExtLenCapExceeded { .. }
        | CryptoError::ArchiveTotalEntryExtCapExceeded { .. } => "resource_cap_exceeded",
        CryptoError::PayloadTampered => "payload_authentication_failed",
        CryptoError::PayloadTruncated => "payload_truncated",
        CryptoError::ExtraDataAfterPayload => "extra_data_after_payload",
        CryptoError::PayloadChunkCountExceeded => "payload_chunk_count_exceeded",
        CryptoError::MalformedArchive { .. } => "malformed_archive",
        CryptoError::UnsafeArchivePath { .. } => "unsafe_archive_path",
        CryptoError::InvalidArchiveTree { .. } => "invalid_archive_tree",
        CryptoError::UnsupportedKeyType { .. } => "unsupported_key_type",
        CryptoError::KeyFileUnlockFailed => "private_key_unlock_failed",
        other => panic!("no diagnostic class mapped for {other:?}"),
    }
}

/// A credential resolved from `credentials.tsv`.
enum Credential {
    Passphrase(String),
    PrivateKey { key_path: PathBuf, unlock: String },
    None,
}

fn read_credentials(root: &Path) -> BTreeMap<String, Credential> {
    let table = read_table(root, "credentials.tsv");
    let mut credentials = BTreeMap::new();
    for row in table.rows {
        let (id, credential) = {
            let id = field(&row, "credential_id").to_string();
            let primary = field(&row, "primary_ref").to_string();
            let secret = field(&row, "secret_ref").to_string();
            let credential = match field(&row, "kind") {
                "passphrase" => Credential::Passphrase(
                    fs::read_to_string(root.join(&primary)).expect("read passphrase credential"),
                ),
                "private_key" => Credential::PrivateKey {
                    key_path: root.join(&primary),
                    unlock: fs::read_to_string(root.join(&secret)).expect("read unlock passphrase"),
                },
                "none" => Credential::None,
                other => panic!("{id}: unknown credential kind {other}"),
            };
            (id, credential)
        };
        assert!(
            credentials.insert(id.clone(), credential).is_none(),
            "credentials.tsv: {id}: duplicate id"
        );
    }
    credentials
}

/// Every `*_ref` column and the `*_sha3_256` column beside it, for the tables
/// that carry them. The payload-key commitment is excluded: §12.3 defines it
/// as a digest of key material rather than of a referenced file.
const DIGEST_PAIRS: &[(&str, &[(&str, &str)])] = &[
    (
        "diagnostic-classes.tsv",
        &[("description_ref", "description_sha3_256")],
    ),
    (
        "credentials.tsv",
        &[
            ("primary_ref", "primary_sha3_256"),
            ("secret_ref", "secret_sha3_256"),
        ],
    ),
    (
        "cases.tsv",
        &[
            ("artifact_ref", "artifact_sha3_256"),
            ("expected_ref", "expected_sha3_256"),
        ],
    ),
    ("errata.tsv", &[("rationale_ref", "rationale_sha3_256")]),
];

#[test]
fn wire_corpus_manifests_are_well_formed() {
    if !corpus_present() {
        return;
    }
    let root = corpus_root();
    assert_eq!(
        fs::read_to_string(root.join("SCHEMA-VERSION"))
            .expect("read SCHEMA-VERSION")
            .trim(),
        "1"
    );
    let revision: u32 = fs::read_to_string(root.join("CORPUS-REVISION"))
        .expect("read CORPUS-REVISION")
        .trim()
        .parse()
        .expect("CORPUS-REVISION is a number");
    assert!(revision >= 1, "revision 0 does not exist");

    // Every committed digest must equal the digest of the bytes its reference
    // names, so a row can never describe a file the corpus does not hold.
    for (table_name, pairs) in DIGEST_PAIRS {
        for row in read_table(&root, table_name).rows {
            for (ref_column, digest_column) in *pairs {
                let reference = field(&row, ref_column);
                let digest = field(&row, digest_column);
                if reference == "-" {
                    assert_eq!(
                        digest, "-",
                        "{table_name}: '-' reference needs a '-' digest"
                    );
                    continue;
                }
                assert!(
                    !reference.contains("..") && !reference.starts_with('/'),
                    "{table_name}: reference {reference} must stay inside the corpus"
                );
                assert_eq!(digest.len(), 64, "{table_name}: digest width");
                assert!(
                    digest
                        .chars()
                        .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()),
                    "{table_name}: digest must be lowercase hexadecimal"
                );
                let bytes = fs::read(root.join(reference))
                    .unwrap_or_else(|e| panic!("{table_name}: read {reference}: {e}"));
                assert_eq!(
                    sha3_hex(&bytes),
                    digest,
                    "{table_name}: {reference} does not match its committed digest"
                );
            }
        }
    }

    // The initial baseline row FORMAT.md §12.3 fixes for revision 1.
    let baselines = read_table(&root, "baselines.tsv");
    assert_eq!(baselines.rows.len(), 1, "revision 1 declares one baseline");
    let baseline = &baselines.rows[0];
    assert_eq!(field(baseline, "baseline_id"), "0.3.0");
    assert_eq!(field(baseline, "established_by_release"), "0.3.0");
    assert_eq!(field(baseline, "parent_baseline_id"), "-");

    let credentials = read_credentials(&root);
    let class_table = read_table(&root, "diagnostic-classes.tsv");
    let credential_table = read_table(&root, "credentials.tsv");
    let origin_table = read_table(&root, "origins.tsv");
    let case_table = read_table(&root, "cases.tsv");
    let errata_table = read_table(&root, "errata.tsv");

    // Every identifier is declared once, and every row was appended by this
    // revision or an earlier one.
    let classes = unique_ids(&class_table, "diagnostic-classes.tsv", "class_id");
    let origins = unique_ids(&origin_table, "origins.tsv", "origin_id");
    let case_ids = unique_ids(&case_table, "cases.tsv", "case_id");
    unique_ids(&credential_table, "credentials.tsv", "credential_id");
    unique_ids(&errata_table, "errata.tsv", "erratum_id");
    for (name, table) in [
        ("baselines.tsv", &baselines),
        ("diagnostic-classes.tsv", &class_table),
        ("credentials.tsv", &credential_table),
        ("origins.tsv", &origin_table),
        ("cases.tsv", &case_table),
    ] {
        assert_revisions_within(table, name, revision);
    }

    for row in &case_table.rows {
        let case_id = field(row, "case_id").to_string();
        assert!(is_manifest_id(&case_id), "{case_id}: identifier grammar");

        let outcome = field(row, "outcome");
        let class = field(row, "diagnostic_class");
        let condition = field(row, "condition_id");
        let expected = field(row, "expected_ref");
        match outcome {
            "reject" => {
                assert_ne!(condition, "-", "{case_id}: reject needs a condition");
                assert!(
                    classes.contains(class),
                    "{case_id}: class {class} undeclared"
                );
                assert_eq!(
                    expected, "-",
                    "{case_id}: reject carries no expected result"
                );
            }
            "accept" | "transcript_equal" => {
                assert_ne!(
                    expected, "-",
                    "{case_id}: non-reject needs an expected result"
                );
                assert_eq!(class, "-", "{case_id}: non-reject uses class '-'");
            }
            other => panic!("{case_id}: unknown outcome {other}"),
        }

        match field(row, "expectation_scope") {
            "invariant" => assert_eq!(field(row, "capability_id"), "-"),
            "capability_relative" => assert_ne!(field(row, "capability_id"), "-"),
            other => panic!("{case_id}: unknown expectation scope {other}"),
        }

        let transcript = field(row, "payload_transcript_kind");
        if field(row, "case_type") == "fcr_decrypt" {
            assert!(
                matches!(transcript, "origins" | "none"),
                "{case_id}: transcript kind"
            );
        } else {
            assert_eq!(transcript, "not_applicable", "{case_id}: transcript kind");
        }
        if transcript == "origins" {
            for origin in field(row, "payload_origin_ids").split(',') {
                assert!(
                    origins.contains(origin),
                    "{case_id}: origin {origin} undeclared"
                );
            }
        } else {
            assert_eq!(
                field(row, "payload_origin_ids"),
                "-",
                "{case_id}: origins list"
            );
        }

        if field(row, "construction") == "mutation" {
            assert_ne!(
                field(row, "parent_case_id"),
                "-",
                "{case_id}: mutation parent"
            );
        } else {
            assert_eq!(
                field(row, "parent_case_id"),
                "-",
                "{case_id}: parent only for mutations"
            );
        }

        let credential = field(row, "credential_id");
        if credential != "-" {
            assert!(
                credentials.contains_key(credential),
                "{case_id}: credential undeclared"
            );
        }
    }

    // Every origin's anchor case exists, and independent origins use distinct
    // nonce prefixes.
    let mut nonces = BTreeSet::new();
    for row in &origin_table.rows {
        let origin_id = field(row, "origin_id");
        assert!(
            case_ids.contains(field(row, "anchor_case_id")),
            "{origin_id}: anchor case is not declared"
        );
        let nonce = field(row, "stream_nonce_hex");
        assert_eq!(
            nonce.len(),
            38,
            "{origin_id}: stream_nonce_hex is a 19-byte prefix"
        );
        assert!(
            nonces.insert(nonce.to_string()),
            "{origin_id}: duplicate nonce prefix"
        );
    }

    // An erratum names an existing case, states a rationale, and takes effect
    // from a revision. §12.3 keeps the affected row and its history in place.
    for row in &errata_table.rows {
        let erratum_id = field(row, "erratum_id");
        assert!(
            case_ids.contains(field(row, "affected_case_id")),
            "{erratum_id}: affected case is not declared"
        );
        let replacement = field(row, "replacement_case_id");
        assert!(
            replacement == "-" || case_ids.contains(replacement),
            "{erratum_id}: replacement case is not declared"
        );
        assert_ne!(
            field(row, "rationale_ref"),
            "-",
            "{erratum_id}: an erratum states its rationale"
        );
        let effective: u32 = field(row, "effective_corpus_revision")
            .parse()
            .unwrap_or_else(|_| panic!("{erratum_id}: effective_corpus_revision is not a number"));
        assert!(effective >= 1, "{erratum_id}: revision 0 does not exist");
    }

    assert_every_file_is_referenced(&root, &origin_table);
}

/// Files that carry the corpus rather than being carried by it, so no row
/// names them.
/// The six manifest tables of `FORMAT.md` §12.3.
const MANIFEST_TABLES: &[&str] = &[
    "baselines.tsv",
    "diagnostic-classes.tsv",
    "credentials.tsv",
    "origins.tsv",
    "cases.tsv",
    "errata.tsv",
];

/// Whether a corpus-relative path carries the corpus rather than being carried
/// by it, so no manifest row names it. A rule rather than a list of names:
/// `tools/` is matched by prefix, so adding a tool needs no edit here nor in
/// the two other checkers that apply the same rule.
fn is_structural_corpus_file(relative: &str) -> bool {
    MANIFEST_TABLES.contains(&relative)
        || matches!(relative, "SCHEMA-VERSION" | "CORPUS-REVISION" | "README.md")
        || relative.starts_with("tools/")
}

/// Every other file must be reachable from a manifest row. The corpus is
/// frozen and append-only, so a file no row names would be committed forever
/// with no digest behind it and no way to notice a change.
fn assert_every_file_is_referenced(root: &Path, origins: &Table) {
    let mut referenced = BTreeSet::new();
    for (table_name, pairs) in DIGEST_PAIRS {
        for row in read_table(root, table_name).rows {
            for (ref_column, _) in *pairs {
                let reference = field(&row, ref_column);
                if reference != "-" {
                    referenced.insert(reference.to_string());
                }
            }
        }
    }
    for row in &origins.rows {
        let reference = field(row, "payload_key_ref");
        if reference != "-" {
            referenced.insert(reference.to_string());
        }
    }

    for path in walk_files(root) {
        let relative = path
            .strip_prefix(root)
            .expect("corpus file is under the corpus root")
            .to_str()
            .expect("corpus path is UTF-8")
            .replace('\\', "/");
        assert!(
            is_structural_corpus_file(&relative) || referenced.contains(&relative),
            "{relative}: no manifest row references this file"
        );
    }
}

/// Every file under `root`, recursively.
fn walk_files(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir).expect("read corpus directory") {
            let path = entry.expect("read corpus entry").path();
            if path.is_dir() {
                stack.push(path);
            } else {
                out.push(path);
            }
        }
    }
    out
}

#[test]
fn wire_corpus_cases_replay() {
    if !corpus_present() {
        return;
    }
    let root = corpus_root();
    let credentials = read_credentials(&root);
    let revision: u32 = fs::read_to_string(root.join("CORPUS-REVISION"))
        .expect("read CORPUS-REVISION")
        .trim()
        .parse()
        .expect("CORPUS-REVISION is a number");
    let withdrawn = cases_withdrawn_by_errata(&root, revision);
    let case_table = read_table(&root, "cases.tsv");
    let mut replayed = 0usize;

    for row in &case_table.rows {
        let case_id = field(row, "case_id");
        // §12.3: an erratum stops the replay asserting its case from the
        // revision it takes effect in; the row itself is never removed.
        if withdrawn.contains(case_id) {
            continue;
        }
        let capability = field(row, "capability_id");
        // §12.2: assert the stored outcome unless this build declares the
        // capability the case depends on.
        if capability != "-" && DECLARED_CAPABILITIES.contains(&capability) {
            continue;
        }
        let artifact = root.join(field(row, "artifact_ref"));
        let credential = credentials
            .get(field(row, "credential_id"))
            .unwrap_or_else(|| panic!("{case_id}: credential not declared"));
        let out = tempfile::tempdir().expect("replay output dir");
        // Each arm returns the byte-exact record the corpus commits for an
        // accepted case, so acceptance proves what was produced rather than
        // only that the operation succeeded.
        let result = match field(row, "case_type") {
            "fcr_decrypt" => decrypt_case(&artifact, credential, out.path()).map(|path| {
                // §12.3: the extracted root kind chooses the comparison. A file
                // root is compared as content; a directory root has no single
                // plaintext, so it is compared as an extraction listing.
                if path.is_dir() {
                    extraction_listing(&path)
                } else {
                    fs::read(path).expect("read decrypted output")
                }
            }),
            "public_key_decode" => PublicKey::from_key_file(&artifact)
                .and_then(|key| key.to_x25519_bytes())
                .map(|material| material.to_vec()),
            "private_key_validate" => validate_private_key_file(&artifact).map(|()| Vec::new()),
            "private_key_open" => {
                let Credential::PrivateKey { unlock, .. } = credential else {
                    panic!("{case_id}: a private_key_open case needs a private-key credential")
                };
                PrivateKey::from_key_file(&artifact, Passphrase::new(unlock.clone()))
                    .into_public_key(ignore_progress)
                    .and_then(|key| key.to_x25519_bytes())
                    .map(|material| material.to_vec())
            }
            // Raw STREAM encryption is not public API, so the known-answer
            // cases are replayed by the library's own `replay_stream_kats`
            // unit test rather than from here.
            "stream_encrypt_kat" => continue,
            other => panic!("{case_id}: replay does not cover case type {other}"),
        };

        match field(row, "outcome") {
            "accept" => {
                let produced =
                    result.unwrap_or_else(|e| panic!("{case_id}: must be accepted, got {e:?}"));
                let expected =
                    fs::read(root.join(field(row, "expected_ref"))).expect("read expected result");
                assert_eq!(
                    produced, expected,
                    "{case_id}: result differs from the committed expectation"
                );
            }
            "reject" => {
                let error = result.expect_err(&format!("{case_id}: must be rejected"));
                assert_eq!(
                    diagnostic_class(&error),
                    field(row, "diagnostic_class"),
                    "{case_id}: rejected with the wrong diagnostic class ({error:?})"
                );
            }
            other => panic!("{case_id}: unexpected outcome {other}"),
        }
        replayed += 1;
    }
    assert!(replayed > 0, "the corpus replayed no cases");
}

/// Builds the extraction listing `FORMAT.md` §12.3 defines for a directory
/// root: one line per extracted object, ordered by path depth and then by path
/// bytes, holding kind, size, content digest, and the archive path.
fn extraction_listing(root: &Path) -> Vec<u8> {
    let root_name = root
        .file_name()
        .expect("extracted root has a name")
        .to_str()
        .expect("extracted root name is UTF-8")
        .to_string();
    let mut objects = Vec::new();
    collect_objects(root, &root_name, &mut objects);
    objects.sort_by(|(a, _), (b, _)| {
        a.split('/')
            .count()
            .cmp(&b.split('/').count())
            .then_with(|| a.cmp(b))
    });
    let mut out = String::new();
    for (path, content) in objects {
        match content {
            Some(bytes) => {
                out.push_str(&format!("f {} {} {path}\n", bytes.len(), sha3_hex(&bytes)))
            }
            None => out.push_str(&format!("d - - {path}\n")),
        }
    }
    out.into_bytes()
}

/// Walks an extracted tree, pairing each archive path with its file content,
/// or with `None` for a directory. Recursion is bounded by the FCA path-depth
/// cap the extraction already enforced.
fn collect_objects(path: &Path, archive_path: &str, out: &mut Vec<(String, Option<Vec<u8>>)>) {
    if path.is_dir() {
        out.push((archive_path.to_string(), None));
        let mut children: Vec<PathBuf> = fs::read_dir(path)
            .expect("read extracted directory")
            .map(|entry| entry.expect("read directory entry").path())
            .collect();
        children.sort();
        for child in children {
            let name = child
                .file_name()
                .expect("extracted entry has a name")
                .to_str()
                .expect("extracted entry name is UTF-8")
                .to_string();
            collect_objects(&child, &format!("{archive_path}/{name}"), out);
        }
    } else {
        out.push((
            archive_path.to_string(),
            Some(fs::read(path).expect("read extracted file")),
        ));
    }
}

/// Named rather than a closure: a `&|_| {}` literal infers a single concrete
/// lifetime, which does not satisfy the callback's higher-ranked bound.
fn ignore_progress(_event: &ProgressEvent) {}

fn decrypt_case(
    artifact: &Path,
    credential: &Credential,
    out: &Path,
) -> Result<PathBuf, CryptoError> {
    match (Decryptor::open(artifact)?, credential) {
        (Decryptor::Passphrase(decryptor), Credential::Passphrase(text)) => decryptor
            .decrypt(Passphrase::new(text.clone()), out, ignore_progress)
            .map(|outcome| outcome.output_path),
        (Decryptor::PrivateKey(decryptor), Credential::PrivateKey { key_path, unlock }) => {
            decryptor
                .decrypt(
                    PrivateKey::from_key_file(key_path, Passphrase::new(unlock.clone())),
                    out,
                    ignore_progress,
                )
                .map(|outcome| outcome.output_path)
        }
        (opened, _) => panic!("credential does not match the classified mode {opened:?}"),
    }
}
